// Generated by CoffeeScript 1.8.0
(function() {
  var buffData, fileToRead, fs, newLines, strData;

  fs = require('fs');

  fileToRead = process.argv[2];

  buffData = fs.readFileSync(fileToRead);

  strData = buffData.toString();

  newLines = strData.split('\n');

  console.log(newLines.length - 1);

}).call(this);
