// Generated by CoffeeScript 1.8.0
(function() {
  var fs;

  fs = require('fs');

  fs.readFile(process.argv[2], function(err, data) {
    return console.log(data.toString().split('\n').length - 1);
  });

}).call(this);
