// Generated by CoffeeScript 1.8.0
(function() {
  var mymodule;

  mymodule = require('./filereadmodule.js');

  mymodule(process.argv[2], process.argv[3], function(err, data) {
    var file, _i, _len, _results;
    if (err) {
      return console.log(err);
    } else {
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        file = data[_i];
        _results.push(console.log(file));
      }
      return _results;
    }
  });

}).call(this);
