// Generated by CoffeeScript 1.8.0
(function() {
  var http, url;

  http = require('http');

  url = process.argv[2];

  http.get(url, function(resp) {
    resp.on('data', function(data) {
      return console.log(data.toString());
    });
    return resp.on('error', function(e) {
      return console.log(e);
    });
  });

}).call(this);
