// Generated by CoffeeScript 1.8.0
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  fs.readdir(process.argv[2], function(err, data) {
    var file, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      file = data[_i];
      if (path.extname(file) === ("." + process.argv[3])) {
        _results.push(console.log(file));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
